Repository Kristrox/CoachHelper, pull requests merged in 2019-07, with the labels that each got.

#24 [Fix] FixFootballField
  app/javascript/components/Ball.jsx
  app/javascript/components/Drop_area.jsx
  app/javascript/components/ball/Movement/index.jsx
  app/javascript/packs/play_book.jsx
Labels: Fix

#56 [Fix] undo arrows after last merge
  .gitignore
  app/assets/images/field.png
  app/assets/images/playgroundfield_background.png
  app/assets/images/t-shirt_enemy.png
  app/assets/images/t-shirt_out_team.png
  app/assets/stylesheets/play_book.scss
  app/assets/stylesheets/play_book_top_tool_bar.scss
  app/javascript/components/DragAndDropOnField.jsx
  app/javascript/components/DrawerField.jsx
  app/javascript/components/Drawing.jsx
  app/javascript/components/TopToolBar.jsx
  app/javascript/components/field.png.old.png
  app/javascript/components/images/field.png
  app/javascript/components/images/tshirt.png
  app/javascript/components/images/tshirto.png
  app/javascript/packs/play_book.jsx
  db/schema.rb
Labels: Add, Fix, Rm

#62 [Fix] Fix Input Name And PlayBook Files
  app/javascript/components/InputName.jsx
  app/javascript/packs/play_book.jsx
Labels: Add

#72 Fix Play Books Show Only To Current User
  app/controllers/play_books_controller.rb
  app/views/application/_sidebar.html.haml
  db/migrate/20190731120854_add_user_to_play_books.rb
  db/schema.rb
Labels: Add, Fix
